MC++: Chebyshev Model Arithmetic for Factorable Functions
Chebyshev Model Arithmetic for Factorable Functions
Classes
class mc::CModel< T >::Exceptions
Exceptions of mc::CModel.
struct mc::CModel< T >::Options
Options of mc::CModel.
Functions
mc::CModel< T >::CModel (const unsigned nvar, const unsigned nord, const bool sparse=false)
Constructor of Chebyshev model environment for nvar variables and order nord
mc::CModel< T >::~CModel ()
Destructor of Chebyshev model environment.
template<typename U >
U ** mc::CModel< T >::get_basis (const unsigned nord, const U *X, const bool scaled=false) const
Get Chebyshev basis functions in U arithmetic for variable array X
template<typename U >
void mc::CModel< T >::get_bndmon (const unsigned nord, U *bndmon, const U *X, const bool scaled=false) const
Get Chebyshev monomial bounds in U arithmetic for variable array X
template<typename U >
void mc::CModel< T >::get_bndmon (const unsigned nord, U *bndmon, const std::set< unsigned > &ndxmon, const U *X, const bool scaled=false) const
Get Chebyshev monomial bounds in U arithmetic for variable array X and monomial indexes in ndxmon
template<typename C , typename U >
U mc::CModel< T >::get_bound (const C *coefmon, const U *const *bndbasis, const U *bndrem, const int type, const std::set< unsigned > &ndxmon=std::set< unsigned >())
Polynomial range bounder using specified bounder type with basis functions bndbasis in U arithmetic and monomial coefficients coefmon in C arithmetic.
void mc::CModel< T >::reset ()
Reset the bounds on Chebyshev basis functions.
CModel< T > * mc::CModel< T >::lift (const unsigned nx, const T *X) const
Lift Chebyshev model by nx extra dimensions with variable bounds X
CModel< T > * mc::CVar< T >::env () const
Get pointer to linked Chebyshev model environment.
mc::CVar< T >::CVar (const double d=0.)
Constructor of Chebyshev variable for a real scalar.
mc::CVar< T >::CVar (const T &B)
Constructor of Chebyshev variable for a remainder bound.
mc::CVar< T >::CVar (CModel< T > *CM, const unsigned ix, const T &X)
Constructor of Chebyshev variable with index ix (starting from 0) and bounded by X
template<typename U >
mc::CVar< T >::CVar (CModel< T > *&CM, const CVar< U > &CV)
Copy constructor of Chebyshev variable in different Chebyshev model environment (with implicit type conversion)
template<typename U >
mc::CVar< T >::CVar (CModel< T > *&CM, const CVar< U > &CV, const T &(U::*method)() const)
Copy constructor of Chebyshev variable in different Chebyshev model environment (with explicit type conversion as given by class member function method)
template<typename U >
mc::CVar< T >::CVar (CModel< T > *&CM, const CVar< U > &CV, T(*method)(const U &))
Copy constructor of Chebyshev variable in different Chebyshev model environment (with explicit type conversion as given by non-class member function method)
mc::CVar< T >::CVar (const CVar< T > &CV)
Copy constructor of Chebyshev variable.
mc::CVar< T >::~CVar ()
Destructor of Chebyshev variable.
CVar< T > & mc::CVar< T >::set (CModel< T > *CM, const unsigned ix, const T &X)
Set Chebyshev variable with index ix (starting from 0) and bounded by X
CVar< T > & mc::CVar< T >::set (CModel< T > *CM, const bool reset=false)
Set Chebyshev model environment in Chebyshev variable to CM
template<typename U >
U mc::CVar< T >::bound (const U *const *bndbasis, const U &bndrem) const
Retreive bound on variable using default bounder in U arithmetic.
template<typename U >
U mc::CVar< T >::bound (const U *const *bndbasis, const U &bndrem, const int type) const
Retreive bound on variable using bounder type in U arithmetic.
double mc::CVar< T >::polynomial (const double *x) const
Evaluate polynomial part at x
double mc::CVar< T >::P (const double *x) const
Shortcut to mc::CVar::polynomial.
CVar< T > mc::CVar< T >::polydiff (const unsigned i) const
Return new Chebyshev variable corresponding to the derivative model with respect to variable i and a zero remainder.
CVar< T > mc::CVar< T >::polynomial () const
Return new Chebyshev variable with same multivariate polynomial part but zero remainder.
CVar< T > mc::CVar< T >::P () const
Shortcut to mc::CVar::polynomial.
CVar< T > & mc::CVar< T >::center ()
Center remainder term of Chebyshev variable.
CVar< T > & mc::CVar< T >::C ()
Shortcut to mc::CVar::center.
double mc::CVar< T >::constant (const bool reset=false)
Get coefficient of constant term in Chebyshev variable. The value of this coefficient is reset to 0 if reset=true, otherwise it is left unmodified (default).
double * mc::CVar< T >::linear () const
Get pointer to array of size nvar with coefficients of linear term in Chebyshev variable. Optional argument X is the actual variable range, e.g. in case some scaling has been applied (see mc::CVar::scale)
double mc::CVar< T >::linear (const unsigned ivar, const bool reset=false)
Get coefficients of linear term for variable ivar in Chebyshev variable. The value of this coefficient is reset to 0 if reset=true, otherwise it is left unmodified (default).
CVar< T > mc::CVar< T >::scale (const T *X) const
Get coefficients of linear term for variable ivar in Chebyshev variable. The value of this coefficient is reset to 0 if reset=true, otherwise it is left unmodified (default). Optional argument Xvar is the actual range for variable ivar, e.g. in case some scaling has been applied (see mc::CVar::scale)
SCModel< T > * mc::SCVar< T >::env () const
Get pointer to linked Chebyshev model environment.
unsigned mc::SCVar< T >::maxord () const
Maximal order of model environment.
unsigned mc::SCVar< T >::nvar () const
Number of variables in model environment.
mc::SCVar< T >::SCVar (SCModel< T > *CM)
Constructor of Chebyshev variable for a real scalar.
mc::SCVar< T >::SCVar (const double d=0., SCModel< T > *CM=0)
Constructor of Chebyshev variable for a real scalar.
mc::SCVar< T >::SCVar (const T &B, SCModel< T > *CM=0)
Constructor of Chebyshev variable for a remainder bound.
mc::SCVar< T >::SCVar (SCModel< T > *CM, const unsigned ix, const T &X)
Constructor of Chebyshev variable with index ix (starting from 0) and bounded by X
mc::SCVar< T >::SCVar (const SCVar< T > &CV)
Copy constructor of Chebyshev variable.
mc::SCVar< T >::~SCVar ()
Destructor of Chebyshev variable.
SCVar< T > & mc::SCVar< T >::set (SCModel< T > *CM, const unsigned ix, const T &X)
Set Chebyshev variable with index ix (starting from 0) and bounded by X
SCVar< T > & mc::SCVar< T >::set (SCModel< T > *CM)
Set environment in Chebyshev model.
template<typename U >
U mc::SCVar< T >::bound (const U *const *bndbasis, const U &bndrem) const
Retreive bound on variable using default bounder in U arithmetic.
template<typename U >
U mc::SCVar< T >::bound (const U *const *bndbasis, const U &bndrem, const int type) const
Retreive bound on variable using bounder type in U arithmetic.
T mc::SCVar< T >::bndord (const unsigned minord) const
Retreive bound on all terms with (total) order minord or higher in polynomial part.
double mc::SCVar< T >::polynomial (const double *x) const
Evaluate polynomial part at x
double mc::SCVar< T >::P (const double *x) const
Shortcut to mc::SCVar::polynomial.
SCVar< T > mc::SCVar< T >::polynomial () const
Return new Chebyshev variable with same multivariate polynomial part but zero remainder.
SCVar< T > mc::SCVar< T >::P () const
Shortcut to mc::SCVar::polynomial.
SCVar< T > & mc::SCVar< T >::center ()
Center remainder term of Chebyshev variable.
SCVar< T > & mc::SCVar< T >::C ()
Shortcut to mc::SCVar::center.
double mc::SCVar< T >::constant (const bool reset=false)
Get coefficient of constant term in Chebyshev variable. The value of this coefficient is reset to 0 if reset=true, otherwise it is left unmodified (default).
double mc::SCVar< T >::linear (const unsigned ivar, const bool reset=false)
Get coefficients of linear term for variable ivar in Chebyshev variable. The value of this coefficient is reset to 0 if reset=true, otherwise it is left unmodified (default).
SCVar< T > & mc::SCVar< T >::scale (const unsigned i, const T &X)
Scale coefficients in Chebyshev variable for the modified range X of variable i.
SCVar< T > & mc::SCVar< T >::scale (const T *X)
Scale coefficients in Chebyshev variable for the modified variable ranges X
SCVar< T > & mc::SCVar< T >::simplify (const double TOL=machprec())
Simplify the model by appending coefficient less than TOL to the remainder term.
Detailed Description
Function Documentation
template<typename T > template<typename U > void mc::CModel< T >::get_bndmon (const unsigned nord, U * bndmon, const U * X, const bool scaled = false) const inline
Get Chebyshev monomial bounds in U arithmetic for variable array X
References mc::PolyModel::_expmon, mc::PolyModel::_nord, mc::PolyModel::_nvar, mc::PolyModel::_posord, mc::CModel< T >::get_basis(), mc::PolyModel::nmon(), and mc::PolyModel::nord().
Referenced by mc::CModel< T >::get_basis(), and mc::CModel< T >::~CModel().
template<typename T > CVar< T > mc::CVar< T >::scale (const T * X) const inline
Scale coefficients in Chebyshev variable for the reduced variable X
References mc::PolyVar< T >::_bndord, mc::PolyVar< T >::_bndord_uptd, mc::PolyVar< T >::_bndpol, mc::PolyVar< T >::_bndrem, mc::PolyVar< T >::_bndT, mc::PolyVar< T >::_center(), mc::PolyVar< T >::_coefmon, mc::PolyVar< T >::_expmon(), mc::PolyVar< T >::_ndxmon, mc::PolyModel::_refvar, mc::PolyModel::_scalvar, mc::PolyVar< T >::_set_bndpol(), mc::PolyVar< T >::_set_bndT(), mc::PolyVar< T >::_unset_bndpol(), mc::PolyVar< T >::_unset_bndT(), mc::PolyVar< T >::B(), mc::CVar< T >::C(), mc::PolyVar< T >::ndxmon(), mc::PolyModel::nmon(), mc::PolyVar< T >::nmon(), mc::PolyModel::nord(), mc::PolyVar< T >::nord(), mc::PolyModel::nvar(), mc::PolyVar< T >::nvar(), mc::CVar< T >::P(), mc::PolyVar< T >::R(), and mc::CVar< T >::set().
Referenced by mc::CVar< T >::linear().